name: promptly

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.7
  image_picker: ^1.0.7
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.5.1
  uuid: ^4.3.3
  cloudinary_public: ^0.23.1
  path_provider: ^2.1.5
  mime: ^2.0.0
  iconsax: ^0.0.8
  cached_network_image: ^3.4.0
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - .env



