// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzQ2cRwk5ohLP9qKGBXn1nm9COxgxyXZ0',
    appId: '1:944959862421:web:933b03a3e5d8da20354d9c',
    messagingSenderId: '944959862421',
    projectId: 'promptly-4e16d',
    authDomain: 'promptly-4e16d.firebaseapp.com',
    storageBucket: 'promptly-4e16d.firebasestorage.app',
    measurementId: 'G-Z8SMP0K419',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATbymq93su1X6Faq052-KTxIklI5qNQxY',
    appId: '1:944959862421:android:bceb428584e3873c354d9c',
    messagingSenderId: '944959862421',
    projectId: 'promptly-4e16d',
    storageBucket: 'promptly-4e16d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbRMMaEiffboGK4cGHnD1CKcWhcaEwEvQ',
    appId: '1:944959862421:ios:25654789f650bc71354d9c',
    messagingSenderId: '944959862421',
    projectId: 'promptly-4e16d',
    storageBucket: 'promptly-4e16d.firebasestorage.app',
    iosClientId: '944959862421-k0rbeud46sth677riau9867u8l88m4n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.promptly',
  );

}